---
name: Run Tests
on:
  pull_request

jobs:
  tests:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Run Tests
        run: |
          xcodebuild -scheme "MyFramework"  -resultBundlePath TestResults test
      - uses: tbartelmess/analyze-xcoderesults-action@0.0.7
        if: always()
        with:
          results: TestResults.xcresult
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
